services:
  db:
    image: postgres:16
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: sirt
    ports: ['5432:5432']
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U postgres']
      interval: 5s
      timeout: 5s
      retries: 10
  api:
    build: ./apps/api
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/sirt?schema=public
      SESSION_SECRET: change_me
      PORT: 4000
    depends_on:
      db:
        condition: service_healthy
    ports: ['4000:4000']
    command: ['node', 'dist/server.js']
